- .github/workflows/deploy.yml
Refactored workflow.
Added job to build backend docker image
> cicd: added backend build job

- .github/workflows/orchestration.yml
- .github/workflows/ui.yml
- ui/README.md
- ui/package.json
Adding the UI github actions workflow to lint and build the frontend application.
closes #38
> workflow to deploy UI

- .github/workflows/orchestration.yml
- ui/src/views/ApplicationPage/ApplicationPage.tsx
- ui/src/views/DataPage/DataPage.tsx
- ui/src/views/DevicesPage/DevicesPage.tsx
- ui/src/views/Home/Home.tsx
- ui/src/views/IdentityPage/IdentityPage.tsx
- ui/src/views/NetworksPage/NetworksPage.tsx
- ui/src/views/PillarTable/PillarTable.query.ts
- ui/src/views/PillarTable/PillarTable.tsx
- ui/src/views/PillarTableHead/PillarTableHead.tsx
Updated pillar name to contain an 'info' icon that provides a description of each pillar. Updated the score to contain the level of each pillar and the level description for it. Added a notes columns to each function pillar. In addition, refactored all function pillar pages. 
closes #41 
closes #40 
closes #39
> feat: Added function description, function explanation, and enhanced score display

- .github/dependabot.yml
- .github/workflows/dependabot.yml
Creating a dependabot.yml file that will create branches to update alerted dependencies that have vulnerabilities.
closes #45
> Creating a Dependabot yaml file to create branches automatically to address outdated dependencies

- backend/cmd/api/internal/auth/middleware.go
- backend/cmd/api/main.go
> feat: added /whoami as endpoint to return encoded jwt of logged in user

- backend/cmd/api/internal/controller/users.go
- backend/cmd/api/internal/graph/graph.go
- backend/cmd/api/internal/graph/users.go
- backend/cmd/api/internal/model/fismasystems.go
- backend/cmd/api/internal/model/users.go
> feat: added users type to graph and related queries

- backend/cmd/api/internal/controller/errors.go
- backend/cmd/api/internal/controller/fismasystems.go
- backend/cmd/api/internal/controller/users.go
- backend/cmd/api/internal/controller/validations.go
- backend/cmd/api/internal/graph/graph.go
- backend/cmd/api/internal/graph/users.go
- backend/cmd/api/internal/model/errors.go
- backend/cmd/api/internal/model/model.go
- backend/cmd/api/internal/model/users.go
> feat: adds ability to create user, includes new error types, and graph response types

- backend/cmd/api/internal/graph/graph.go
- backend/cmd/api/internal/model/users.go
- backend/db-schema.sql
- infrastructure/verified-access.tf
also ensures verified access checks correct job code
closes #68
> refactor: current_role to role

- infrastructure/data.tf
- infrastructure/ecs.tf
- infrastructure/locals.tf
- infrastructure/oidc.tf
- infrastructure/terraform.tf
- infrastructure/tfvars/dev.tfvars
- infrastructure/tfvars/prod.tfvars
- infrastructure/variables.tf
- infrastructure/verified-access.tf
> refactor: use conditional expression for job code in policy 

- infrastructure/ec2.tf
- infrastructure/ecr.tf
- infrastructure/oidc.tf
- infrastructure/rds.tf
- infrastructure/verified-access.tf
Outputs are not used programmatically and only serve to expose information in logs
> refactor: removed outputs

- backend/cmd/api/internal/controller/functionscores.go
- backend/cmd/api/internal/graph/functionscores.go
- backend/cmd/api/internal/graph/graph.go
- backend/cmd/api/internal/model/functionscores.go
- backend/cmd/api/internal/model/users.go
- backend/db-schema.sql
> feat: added ability to save function scores

- backend/cmd/api/internal/auth/middleware.go
- backend/cmd/api/internal/controller/users.go
- backend/cmd/api/internal/graph/graph.go
- backend/cmd/api/internal/graph/users.go
- backend/cmd/api/internal/model/users.go
- backend/db-schema.sql
- infrastructure/tfvars/dev.tfvars
- infrastructure/tfvars/prod.tfvars
- infrastructure/variables.tf
- infrastructure/verified-access.tf
> feat: adds ability to assign and unassign list of fismasystemids to user

- backend/cmd/api/internal/graph/functionscores.go
- backend/cmd/api/internal/graph/graph.go
- backend/cmd/api/internal/graph/response.go
- backend/cmd/api/internal/graph/users.go
We love DRY code here.
closes #76
> refactor: response struct now has methods for error and response codes

- backend/cmd/api/internal/auth/middleware.go
- backend/cmd/api/internal/controller/datacalls.go
- backend/cmd/api/internal/model/datacalls.go
- backend/cmd/api/internal/router/router.go
- backend/db-schema.sql
this also moves all routes to /api/v1
> feat: added route for datacalls

- backend/cmd/api/internal/router/router.go
- infrastructure/alb-public.tf
- infrastructure/cloudfront.tf
> feat: added login to redirect to IDM/Okta

- infrastructure/tfvars/prod.tfvars
setting prod container count to 1
> chore: scaling prod api container count

- backend/cmd/api/internal/controller/scores.go
- backend/cmd/api/internal/model/scores.go
- backend/cmd/api/internal/router/router.go
This returns a list of score aggregate which are the avg score by datacall and fisma system
closes #101
> feat: added scores/aggregate

- .github/workflows/analysis.yml
- .github/workflows/backend.yml
- .github/workflows/infrastructure.yml
- .github/workflows/orchestration-dev.yml
- .github/workflows/orchestration-prod.yml
- .gitignore
- README.md
- backend/Dockerfile
- backend/README.md
- backend/go.mod
> integrate Snyk CLI into CICD pipeline

- backend/cmd/api/internal/controller/questions.go
- backend/cmd/api/internal/model/questions.go
- backend/cmd/api/internal/router/router.go
- controller.SaveQuestion
- controller.GetQuestionByID
- model.FindQuestionByID
- (model.Question).Save()
- refactored previous handling of FindQuestions to be clearly FindQuestionsByFismaSystem since they serve 2 different purposes. FindQuestions is for admin management, and the latter is for users listing questions with joined data such as function and pillar
closes #129
> feat: admins have ability to add and edit questions

- .github/workflows/backend.yml
- backend/_test_data.sql
- backend/cmd/api/internal/controller/controller.go
- backend/cmd/api/internal/controller/functions.go
- backend/cmd/api/internal/migrations/000_initial_schema.go
- backend/cmd/api/internal/migrations/003_ordering_columns_functions.go
- backend/cmd/api/internal/model/errors.go
- backend/cmd/api/internal/model/fismasystems.go
- backend/cmd/api/internal/model/functions.go
- backend/cmd/api/internal/model/users.go
- backend/cmd/api/internal/model/usersfismasystems.go
- backend/cmd/api/internal/model/validations.go
- backend/cmd/api/internal/router/router.go
- router paths to manage functions 
- model.isValidIntId function
- model.Function methods
- migration to add order column to functions
- functions controller
- InvalidInputError.data is now map[string]any to allow for any type value not just strings
- removed error printing from controller
closes #151
> feat: ability to list, add, and edit  functions and function options

- .github/workflows/analysis.yml
- .github/workflows/backend.yml
- backend/.snyk
- backend/go.mod
Added snyk policy to ignore [this vulnerability](https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTTPHTTPPROXY-9058601) in an irrelevant package that is not used by the application
> fix: update dependencies to address vulnerability in golang.org/x/net/http/httpproxy

- .github/workflows/backend.yml
- backend/Dockerfile
- backend/_test_data.sql
- backend/cmd/api/internal/migrations/008_users_role.go
- backend/emberfall_tests.yml
- migration to change user.role from char to varchar to remove padding in return values
- Rewrote the smoke tests to cover most of the api routes
closes #162
> cicd: exhaustive api tests based on emberfall v0.3.1

- backend/cmd/api/internal/controller/controller.go
- backend/cmd/api/internal/model/errors.go
- backend/cmd/api/internal/model/scores.go
- validate method to model/score struct to check if related datacall deadline has passed
none
closes #185
> fix: validate to check whether datacall deadline has passed

- backend/_test_data.sql
- backend/cmd/api/internal/model/users.go
- backend/emberfall_tests.yml
nothing new
- refactored model to ensure that all find by email is case-insensitive
- change case of emails in test db sql and emberfall test to ensure tests still pass
closes #196
> fix: resolve an issue where email look ups fail because of case sensitivity

- backend/cmd/api/internal/controller/datacalls.go
- backend/cmd/api/internal/model/datacalls.go
- backend/cmd/api/internal/router/router.go
- backend/emberfall_tests.yml
- new route `datacalls/latest` to retrieve the latest without needing to first retrieve the entire list
- controller function
- model function
- new emberfall test
none
closes #203
> feat: implemented datacalls/latest including test

- backend/cmd/api/internal/mail/mail.go
none
- update email message to include `From: ` header
closes #214
> fix: resolves issue where lack of From header caused gmail to bounce

- .gitignore
- backend/cmd/lambda/main.go
- backend/go.mod
- backend/go.sum
- backend/internal/notifications/slack.go
- infrastructure/iam.tf
- infrastructure/lambda.tf
- infrastructure/secrets.tf
Implements comprehensive Slack notifications for ZTMF data sync results, providing real-time alerts for both success and failure scenarios critical for government analytics data integrity.
ASM secret supports multiple webhook URLs:
```json
{
"primary": "https://hooks.slack.com/services/YOUR/PRIMARY/WEBHOOK",
"secondary": "https://hooks.slack.com/services/YOUR/SECONDARY/WEBHOOK", 
"critical": "https://hooks.slack.com/services/YOUR/CRITICAL/WEBHOOK"
}
```
- **DEV**: "Weekly" sync notifications  
- **PROD**: "Quarterly" sync notifications
- **Dynamic Quarter**: Auto-calculates current quarter (Q1-Q4 YYYY)
```
✅ ZTMF Data Sync SUCCESS (PROD - Quarterly)
📊 10 tables synced: 23,648 rows
⏱️ Duration: 2m19s
📅 Q3 2025 data now available in Snowflake
```
```
🚨 ZTMF Data Sync FAILURE (DEV - Weekly) …
```
> Add Slack notifications for ZTMF data sync monitoring
