CMS-Enterprise/ztmf

.github/workflows/backend.yml, .github/workflows/orchestration.yml, backend/Dockerfile, backend/cmd/api/handler.go, backend/cmd/api/main.go, infrastructure/alb.tf
Added `ELBSecurityPolicy-TLS13-1-3-FIPS-2023-04` security policy to ALB
Configured HTTP listener to use TLS 1.3 and log TLS version and cipher for all requests
fixes #50
=> fix: ensure api and load balancer are FIPS compliant 

backend/cmd/api/internal/controller/users.go, backend/cmd/api/internal/graph/graph.go, backend/cmd/api/internal/graph/users.go, backend/cmd/api/internal/model/users.go
=> refactor: createUser to saveUser, and added update function to model

backend/cmd/api/internal/auth/token.go
Fixes an issue where keys after the first were never cached, and since the return pulls from the cache it returned nil which caused the token validator to error
=> fix: removed once.Do which was only caching first key

README.md, backend/cmd/api/internal/controller/users.go, backend/cmd/api/internal/controller/whoami.go, backend/cmd/api/internal/router/router.go, infrastructure/alb-public.tf, infrastructure/cloudfront.tf
`/whoami` was returning a JWT from which the email was then used to call `/users/<email>`
The issues with this were that
- because OIDC auth is handled by the ALB, which acts as a "Backend for Frontend" token handler, the client should only be concerned with the token handler session cookie and never receive a JWT
- /whoami is not RESTful in that it was not returning a resource
`/users/current` DOES return a resource, the object of a single user which is identified by way of the token which is forwarded to the api by the token handler mapped to the session cookie
=> refactor: replace /whoami with /users/current

.github/workflows/orchestration-prod.yml
always build and deploy binary for every merge to main
=> fix: remove diff check

infrastructure/cloudfront.tf, infrastructure/data.tf
this applies the CMS cloud preconfigured WAF to the cloudfront distribution
closes #95
=> feat: added web acl to cloudfront

backend/cmd/api/internal/router/router.go
/users/current was being matched to /users/{userid:} leading the UI into an infinite redirect loop to /login
=> fix: resolves an issue where /users/current wasnt matching correctly

compose.yml
Adding a platform flag in compose file for Apple Silicon users to run when building and running docker container.
Closes #119 
None
compose.yml to have the platform flag
None
None
=> Providing a platform flag for the backend

backend/cmd/api/internal/controller/controller.go, backend/cmd/api/internal/controller/errors.go, backend/cmd/api/internal/controller/users.go, backend/cmd/api/internal/controller/usersfismasystems.go, backend/cmd/api/internal/model/errors.go, backend/cmd/api/internal/model/usersfismasystems.go, backend/cmd/api/internal/router/router.go
This introduces the `assignedfismasystems` as a distinct resource apart from `fismasystems`
The following routes and functionality are included:
`GET /users/{userid}/assignedfismasystems` returns a list of fismasystem ids
`POST /users/{userid}/assignedfismasystems` creates a record of the assignment using the following body
```
{"fismasystemid": <int>}
```
`DELETE /users/{userid}/assignedfismasystems/{fismasystemid}` deletes the assignment
=> feat: added ability to list, add, and delete users assigned fismasystems

.github/workflows/backend.yml, backend/_test_data.sql, backend/actions-compose.yml, backend/cmd/api/internal/migrations/migrations.go, backend/cmd/api/internal/migrations/populate.go, backend/internal/config/config.go
Implements mechanism to populate a test database with dummy data. If `DB_POPULATE` env var is set to a path, migrations will load that file and execute the SQL contained therein.
The backend test was also modified to include a volume to allow the docker compose container access to the test data sql file
closes #144
=> feat: imeplemented test db population

.github/workflows/backend.yml, .github/workflows/orchestration-dev.yml
closes #137 
Temporarily disabled the if diff check to force backend to run. Do not merge until tests pass and check is reverted
=> cicd: smoke test all API urls 

backend/cmd/api/internal/controller/controller.go, backend/cmd/api/internal/controller/fismasystems.go, backend/cmd/api/internal/migrations/002_fix_datacenter_spelling.go, backend/cmd/api/internal/model/errors.go, backend/cmd/api/internal/model/fismasystems.go, backend/cmd/api/internal/model/validations.go, backend/cmd/api/internal/router/router.go
- 2 new routes: `POST fismasystems` and `PUT fismasystems/<id>` to create and update
- `SaveFismaSystem()` function to controller
- `isValid()`, `Save()`, `insertSql()`, and `updateSql()` methods to `*model.FismaSystem`
- migration to correct spelling of datacenterenvironment ("DECOMISSIONED" -> "DECOMMISSIONED")
- refactored handling of fismasystem columns to reduce repetition
- refactored error handling to ensure `model.InvalidInputError` is properly returned
- included list of valid datacenter environments
closes #146
=> feat: admins can add and edit fismasystems

backend/cmd/api/internal/controller/datacalls.go, backend/cmd/api/internal/controller/functions.go, backend/cmd/api/internal/controller/users.go, backend/cmd/api/internal/migrations/004_datacalls_new_columns.go, backend/cmd/api/internal/model/datacalls.go, backend/cmd/api/internal/router/router.go
- routes for datacalls crud
- model.FindDataCallByID
- `dataCallColumns` as an array of column names to reduce repetition
- `(*DataCall).fields()` as a private method to reduce repetition when calling `row.Scan`
- migration to add new fields to datacalls table
- `model.GetUserByID` and `model.GetFunctionByID` to conform to naming conventions
closes #146
=> feat: ability to add and edit datacalls

backend/cmd/api/internal/model/validations.go
Nothing new
model validations `isValidUUID` now tests for the absence of dashes. If none were found it matches against a no dash version. This is because _some_ records of fisma systems do not include dashes in the UUID value
closes #155
=> refactor: UUID validation supports values without dashes

.github/workflows/orchestration-dev.yml, backend/cmd/api/internal/auth/middleware.go, backend/cmd/api/internal/controller/controller.go, backend/cmd/api/internal/controller/datacalls.go, backend/cmd/api/internal/controller/fismasystems.go, backend/cmd/api/internal/controller/functions.go, backend/cmd/api/internal/controller/questions.go, backend/cmd/api/internal/controller/scores.go, backend/cmd/api/internal/controller/users.go, backend/cmd/api/internal/controller/usersfismasystems.go, backend/cmd/api/internal/migrations/005_user_events.go, backend/cmd/api/internal/model/answers.go, backend/cmd/api/internal/model/contextkey.go, backend/cmd/api/internal/model/datacalls.go, backend/cmd/api/internal/model/errors.go, backend/cmd/api/internal/model/events.go, backend/cmd/api/internal/model/fismasystems.go, backend/cmd/api/internal/model/functionoptions.go, backend/cmd/api/internal/model/functions.go, backend/cmd/api/internal/model/model.go, backend/cmd/api/internal/model/questions.go, backend/cmd/api/internal/model/scores.go, backend/cmd/api/internal/model/users.go, backend/cmd/api/internal/model/usersfismasystems.go
events table via migration
all inserts, updates, and deletes are recorded as events
Refactored entire model package to pass squirrel builders to `query` and `queryRow`, centralizing the builder.ToSQL method, which allows event sourcing to be centralized. Refactored majority of model methods to use the new signatures for `query` and `queryRow` which greatly simplified those functions and reduced repitition
closes #132
=> feat: api logs user events

backend/cmd/api/internal/migrations/006_scores_datacall_constraint.go, backend/cmd/api/internal/model/datacalls.go, backend/cmd/api/internal/model/scores.go
- migration to ensure proper foreign key constraint on `scores.datacallid`
- function in `model` to find previous datacall
- function in `model` to copy scores from the previous datacall
closes #164
=> feat: creating new datacall now copies scores associated to previous datacall

backend/cmd/api/internal/controller/datacalls.go, backend/cmd/api/internal/controller/events.go, backend/cmd/api/internal/controller/functions.go, backend/cmd/api/internal/controller/scores.go, backend/cmd/api/internal/model/answers.go, backend/cmd/api/internal/model/functions.go, backend/cmd/api/internal/model/scores.go
nothing new
Replaced complex retrieval and conversion of query string parameters with `decoder.Decode` and applied relevant `schema` tags to model input structs
closes #165
=> refactor:  use gorilla/schema decoder in all controllers where r.URL.Query() is needed

infrastructure/cloudfront.tf
nothing new
Set minimum TLS protocol for CloudFront
=> fix: increase minimum TLS version to 1.2 in CloudFront distribution

backend/internal/secrets/secrets.go
nothing new
- refactored secrets library to refresh secrets if they were within 23 hours of the next rotation date because secrets manager has been known to rotate secrets as much as 16 hours in advance
closes #178
=> fix: refresh secrets if within 23 hours of next rotation date

backend/_test_data.sql, backend/cmd/api/internal/auth/middleware.go, backend/cmd/api/internal/controller/controller.go, backend/cmd/api/internal/controller/users.go, backend/cmd/api/internal/migrations/008_users_soft_delete.go, backend/cmd/api/internal/model/users.go, backend/cmd/api/internal/router/router.go, backend/emberfall_tests.yml
- migration to add `delete` column to users table
- model/users FindUsers() now returns only users where delete=false
- auth now returns http 401 unauthorized when deleted user tries to log in
closes #184
=> implemented soft delete feature for users resource

.github/workflows/orchestration-dev.yml, backend/cmd/api/internal/controller/users.go, backend/cmd/api/internal/model/users.go, backend/emberfall_tests.yml
- model/users `FindUsersInput` type
- `controller.ListUsers` now hydrates `FindUsersInput` and passes to `model.FindUsers`
- `model.FindUsers` now filters based on all fields of `FindUsersInput` that are present in the request
To filter list of users, append the following query string parameters in any order in any combination:
`?role=string&email=string&fullname=string&deleted=bool`
`role` and `deleted` will be used as an exact match
`email` and `fullname` will be used as a loose match e.g.: `email=cms.hss.gov` will return all users with that as part of their email, `fullname=bob` will return all users with "bob" anywhere in their name
closes #189
=> feat: ability to filter list of users via query string parameters

backend/cmd/api/internal/migrations/0013datacallsunique.go
- migration to add unique constraint to datacalls.datacall
This will ensure that no 2 datacalls will share the same name 
none
closes #195
=> refactor: added unique constraint to datacalls.datacall

backend/cmd/api/internal/migrations/0014usersemailuniqueindex.go
- migration to remove the unique constraint which is case-sensitive, and replace with a unique index bound to the lower() function for case-insensitive uniqueness
DB schema as mentioned above
closes #201
=> fix: added unique email index to users

infrastructure/rds.tf
AWS automatically upgraded the RDS Aurora PostgreSQL cluster from version 16.1 to 16.6 during a maintenance window. When Terraform tries to deploy, it attempts to "correct" this by downgrading back to 16.1, which AWS RDS does not allow.
**Error encountered:**
```
Error: updating RDS Cluster (ztmf): operation error RDS: ModifyDBCluster, 
https response error StatusCode: 400, RequestID: 2e33d1fc-835f-4768-9f19-6791e7028602, 
api error InvalidParameterCombination: Cannot upgrade aurora-postgresql from 16.6 to 16.1
```
Update the Terraform configuration to match the current AWS reality by changing `engine_version` from "16.1" to "16.6" in the RDS cluster resource.
- Updated `infrastructure/rds.tf` PostgreSQL engine version from 16.1 to 16.6
- No functional changes to the database or …
=> fix: update PostgreSQL engine version to 16.6
